version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/joshdk/aws-console)

linters:
  default: all

  disable:
    # Linters which are not used for this project:
    - depguard
    - err113
    - exhaustruct
    - lll
    - noinlineerr
    - tagliatelle
    - wrapcheck

    # Linters which are deprecated:
    - wsl

  settings:
    goheader:
      template: |-
        Copyright Josh Komoroske. All rights reserved.
        Use of this source code is governed by the MIT license,
        a copy of which can be found in the LICENSE.txt file.
        SPDX-License-Identifier: MIT
