version: 2

builds:
  - goos:
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

    flags:
      - -buildvcs=false
      - -trimpath

    ldflags:
      - -X github.com/joshdk/aws-console/cmd.revision={{ .FullCommit }}
      - -X github.com/joshdk/aws-console/cmd.timestamp={{ .Date }}
      - -X github.com/joshdk/aws-console/cmd.version={{ .Summary }}
      - -buildid=
      - -s
      - -w

    env:
      - CGO_ENABLED=0

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  name_template: "{{ .Tag }} Release"
  prerelease: auto

changelog:
  disable: true

checksum:
  disable: true

homebrew_casks:
  - description: Generate a temporary login URL for the AWS Console
    homepage: https://github.com/joshdk/aws-console
    license: MIT

    commit_author:
      name: Josh Komoroske
      email: jdkomo@gmail.com

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/{{ .ProjectName }}"]
          end

    repository:
      owner: joshdk
      name: homebrew-tap

      git:
        url: git@github.com:joshdk/homebrew-tap.git
        private_key: "{{ .Env.HOMEBREW_DEPLOY_KEY }}"
