project_name: aws-console

builds:
  - id: aws-console
    binary: aws-console

    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64

    flags:
      - -buildvcs=false
      - -trimpath

    ldflags:
      - -s -w
      - -buildid=
      - -X jdk.sh/meta.date={{ .Date }}
      - -X jdk.sh/meta.sha={{ .Commit }}
      - -X jdk.sh/meta.version={{ .Tag }}

    env:
      - CGO_ENABLED=0

archives:
  - id: aws-console
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  name_template: "{{ .Tag }} Release"
  prerelease: auto

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true

brews:
  - name: aws-console

    tap:
      owner: joshdk
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"

    url_template: "https://github.com/joshdk/aws-console/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_msg_template: "feat: brew formula update for {{ .ProjectName }} {{ .Tag }}"
    commit_author:
      name: Josh Komoroske
      email: jdkomo@gmail.com

    folder: Formula

    caveats: "Run aws-console --help for usage"
    homepage: "https://github.com/joshdk/aws-console"
    description: "Generate a temporary login URL for the AWS Console"
    license: "MIT"

    test: |
      system "#{bin}/aws-console --version"
